# https://circleci.com/docs/2.0/config-intro/
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
# https://circleci.com/docs/2.0/tutorials/#sample-apps-with-companion-guides
version: 2
jobs:
  test-job:
    docker:
      - image: circleci/python:2.7.16-jessie-browsers
    steps:
      - checkout
      - run:
          name: INSTALL DEPENDENCY
          command: |
            pip install -U setuptools
            pip install --user -r requirements.txt -r test-requirements.txt
      - run: ~/.local/bin/nosetests
  deploy-job:
    docker:
      - image: circleci/python:2.7.16-jessie-browsers
    steps:
      - checkout
      - run:
          name: DEPLOY
          command: |
            pip install -U setuptools
            pip install --user -r requirements.txt
            pip install --user twine s3pypi
            python setup.py sdist bdist_wheel
            ~/.local/bin/twine upload --skip-existing -u meiqia -p "${PYPI_PASSWORD}" dist/*
            ~/.local/bin/s3pypi --region "${AWS_REGION}" --bucket "${AWS_S3_BUCKET}"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-job
  build-and-deploy:
    jobs:
      - deploy-job:
          filters:
            # only tags, no branches
            tags:
              only: /^([0-9]+)(\.[0-9]+)*$/
            branches:
              ignore: /.*/
